apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opf-app-of-apps-osc-cl1
spec:
  destination:
    namespace: argocd
    name: moc-infra
  project: operate-first
  source:
    path: envs/osc/osc-cl1
    repoURL: https://github.com/operate-first/argocd-apps.git
    targetRevision: HEAD
