---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kfdefs
spec:
  destination:
    name: devconfus2021
    namespace: opendatahub
  project: cluster-management
  source:
    path: kfdefs/overlays/emea/devconfus2021
    repoURL: https://github.com/operate-first/apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - ApplyOutOfSyncOnly=true
