---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opf-kubeflow
spec:
  destination:
    name: devconfus2021
    namespace: kubeflow
  project: operate-first
  source:
    path: kubeflow-components/overlays/emea/devconfus2021
    repoURL: https://github.com/operate-first/apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
