---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opendatahub-operator
spec:
  destination:
    name: devconfus2021
    namespace: opendatahub-operator
  project: operate-first
  source:
    path: odh-operator/overlays/emea/devconfus2021
    repoURL: https://github.com/operate-first/apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
